// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CatalogService.Infrastructure
{
    public partial class SP_Product_GetByIdResult
    {
        public int ProductId { get; set; }
        [StringLength(250)]
        public string Name { get; set; }
        [StringLength(250)]
        public string Slug { get; set; }
        [StringLength(1000)]
        public string ShortDescription { get; set; }
        [StringLength(2147483647)]
        public string LongDescription { get; set; }
        public int? BrandId { get; set; }
        public int? ManufacturerId { get; set; }
        public int? CategoryId { get; set; }
        public int? DefaultSkuId { get; set; }
        public byte Status { get; set; }
        public bool IsSearchable { get; set; }
        [Column("Weight", TypeName = "decimal(9,3)")]
        public decimal? Weight { get; set; }
        [StringLength(200)]
        public string Dimensions { get; set; }
        [StringLength(1000)]
        public string PrimaryImageUrl { get; set; }
        [StringLength(250)]
        public string SeoTitle { get; set; }
        [StringLength(500)]
        public string SeoDescription { get; set; }
        [StringLength(500)]
        public string SeoKeywords { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        [StringLength(100)]
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        [StringLength(200)]
        public string BrandName { get; set; }
        [StringLength(200)]
        public string CategoryName { get; set; }
    }
}
