// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CatalogService.Infrastructure
{
    public partial class SP_ProductSearch_BySkuResult
    {
        public int ProductId { get; set; }
        [StringLength(250)]
        public string Name { get; set; }
        [StringLength(250)]
        public string Slug { get; set; }
        public int SkuId { get; set; }
        [StringLength(100)]
        public string Sku { get; set; }
        [Column("UnitPrice", TypeName = "decimal(18,2)")]
        public decimal UnitPrice { get; set; }
        [StringLength(10)]
        public string Currency { get; set; }
        [StringLength(200)]
        public string CategoryName { get; set; }
    }
}
