// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CatalogService.Infrastructure
{
    public partial class SP_Stats_GetSummaryResult
    {
        public int? TotalProducts { get; set; }
        public int? TotalSkus { get; set; }
        public int? TotalCategories { get; set; }
        public int? PendingOutbox { get; set; }
    }
}
