// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class BulkImportJob
{
    public int JobId { get; set; }

    public string FileName { get; set; }

    public int TotalRows { get; set; }

    public int ProcessedRows { get; set; }

    public int FailedRows { get; set; }

    public byte Status { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<BulkImportItem> BulkImportItems { get; set; } = new List<BulkImportItem>();
}