// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class BulkImportItem
{
    public int ItemId { get; set; }

    public int JobId { get; set; }

    public int RowNumber { get; set; }

    public byte Status { get; set; }

    public string ErrorMessage { get; set; }

    public string Data { get; set; }

    public virtual BulkImportJob Job { get; set; }
}