// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class Inbox
{
    public int InboxId { get; set; }

    public string MessageId { get; set; }

    public DateTime ProcessedOn { get; set; }

    public string Handler { get; set; }
}