// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class InventorySnapshot
{
    public int SnapshotId { get; set; }

    public int SkuId { get; set; }

    public string WarehouseId { get; set; }

    public int QuantityAvailable { get; set; }

    public int QuantityReserved { get; set; }

    public DateTime LastUpdated { get; set; }

    public virtual ProductVariant Sku { get; set; }
}