// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class Manufacturer
{
    public int ManufacturerId { get; set; }

    public string Name { get; set; }

    public string ContactInfo { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}