// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class Outbox
{
    public int OutboxId { get; set; }

    public DateTime OccurredOn { get; set; }

    public string EventType { get; set; }

    public string Payload { get; set; }

    public bool Processed { get; set; }

    public DateTime? ProcessedOn { get; set; }

    public int RetryCount { get; set; }

    public string CorrelationId { get; set; }
}