// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class PriceHistory
{
    public int PriceHistoryId { get; set; }

    public int? ProductId { get; set; }

    public int? SkuId { get; set; }

    public decimal? OldPrice { get; set; }

    public decimal NewPrice { get; set; }

    public string Currency { get; set; }

    public string ChangedBy { get; set; }

    public DateTime ChangedDate { get; set; }
}