// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class ProductAttribute
{
    public int ProductAttributeId { get; set; }

    public int ProductId { get; set; }

    public string Key { get; set; }

    public string ValueString { get; set; }

    public decimal? ValueNumber { get; set; }

    public DateTime? ValueDate { get; set; }

    public bool? ValueBoolean { get; set; }

    public bool IsSearchable { get; set; }

    public virtual Product Product { get; set; }
}