// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class ProductRelationship
{
    public int ParentProductId { get; set; }

    public int RelatedProductId { get; set; }

    public byte RelationshipType { get; set; }

    public int SortOrder { get; set; }

    public virtual Product ParentProduct { get; set; }

    public virtual Product RelatedProduct { get; set; }
}