// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class ProductVariant
{
    public int SkuId { get; set; }

    public int ProductId { get; set; }

    public string Sku { get; set; }

    public string Barcode { get; set; }

    public string Attributes { get; set; }

    public decimal UnitPrice { get; set; }

    public string Currency { get; set; }

    public decimal? CompareAtPrice { get; set; }

    public decimal? CostPrice { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public virtual ICollection<InventorySnapshot> InventorySnapshots { get; set; } = new List<InventorySnapshot>();

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();
}