// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class ProductReview
{
    public int ReviewId { get; set; }

    public int ProductId { get; set; }

    public string UserId { get; set; }

    public byte Rating { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public bool IsPublished { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Product Product { get; set; }
}