// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CatalogService.Domain.Entities;

public partial class VwProductSearch
{
    public int ProductId { get; set; }

    public string Name { get; set; }

    public string Slug { get; set; }

    public string ShortDescription { get; set; }

    public string PrimaryImageUrl { get; set; }

    public string SeoTitle { get; set; }

    public string SeoDescription { get; set; }

    public string SeoKeywords { get; set; }

    public byte Status { get; set; }

    public int? CategoryId { get; set; }

    public string CategoryName { get; set; }

    public int? BrandId { get; set; }

    public string BrandName { get; set; }

    public int? SkuId { get; set; }

    public string Sku { get; set; }

    public decimal? UnitPrice { get; set; }

    public string Currency { get; set; }

    public int QuantityAvailable { get; set; }
}