// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class CartAdjustment
{
    public int Id { get; set; }

    public long? CartId { get; set; }

    public int? CartItemId { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public decimal Amount { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual CartItem CartItem { get; set; }
}