// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class CartItemOption
{
    public int Id { get; set; }

    public int CartItemId { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

    public virtual CartItem CartItem { get; set; }
}