// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class CartLock
{
    public long CartId { get; set; }

    public string LockedBy { get; set; }

    public DateTime LockedAt { get; set; }

    public string Reason { get; set; }

    public virtual Cart Cart { get; set; }
}