// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class CartTaxis
{
    public int Id { get; set; }

    public long CartId { get; set; }

    public string Jurisdiction { get; set; }

    public decimal? Rate { get; set; }

    public decimal Amount { get; set; }

    public bool IncludedInPrice { get; set; }

    public string ItemizedJson { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Cart Cart { get; set; }
}