// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class CartPayment
{
    public int Id { get; set; }

    public long CartId { get; set; }

    public string Method { get; set; }

    public decimal AmountAuthorized { get; set; }

    public string CurrencyCode { get; set; }

    public string Status { get; set; }

    public DateTime UpdatedDate { get; set; }

    public virtual Cart Cart { get; set; }
}