// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class CartCoupon
{
    public int Id { get; set; }

    public long CartId { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public decimal DiscountAmount { get; set; }

    public bool IsApplied { get; set; }

    public DateTime AppliedDate { get; set; }

    public string Source { get; set; }

    public virtual Cart Cart { get; set; }
}