// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class CartEvent
{
    public long Id { get; set; }

    public long CartId { get; set; }

    public string EventType { get; set; }

    public string DataJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public virtual Cart Cart { get; set; }
}