// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class InboxMessage
{
    public long Id { get; set; }

    public string MessageId { get; set; }

    public string MessageType { get; set; }

    public DateTime ReceivedOn { get; set; }

    public DateTime? ProcessedOn { get; set; }

    public string Status { get; set; }

    public string Consumer { get; set; }

    public string Content { get; set; }
}