// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class OutboxMessage
{
    public long Id { get; set; }

    public DateTime OccurredOn { get; set; }

    public string MessageId { get; set; }

    public string Type { get; set; }

    public string Destination { get; set; }

    public string Content { get; set; }

    public bool Processed { get; set; }

    public DateTime? ProcessedOn { get; set; }

    public int RetryCount { get; set; }

    public string LockedBy { get; set; }

    public DateTime? LockedAt { get; set; }
}