// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CartService.Domain.Entities;

public partial class SavedForLaterItem
{
    public int Id { get; set; }

    public long CartId { get; set; }

    public int ItemId { get; set; }

    public string Sku { get; set; }

    public string ProductName { get; set; }

    public decimal UnitPrice { get; set; }

    public int Quantity { get; set; }

    public string ProductSnapshotJson { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Cart Cart { get; set; }
}