// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StockService.Infrastructure.Models
{
    public partial class SP_GetStockAgingSummaryResult
    {
        public Guid StockItemId { get; set; }
        public Guid ProductId { get; set; }
        public Guid WarehouseId { get; set; }
        public int AvailableQuantity { get; set; }
        public int? DaysInStock { get; set; }
    }
}
