// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StockService.Infrastructure.Models
{
    public partial class SP_GetInventoryTurnoverResult
    {
        public Guid StockItemId { get; set; }
        public int? TotalOutbound { get; set; }
        [Column("AverageCost", TypeName = "decimal(38,6)")]
        public decimal? AverageCost { get; set; }
    }
}
