// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CartService.Infrastructure
{
    public partial class SP_Cart_GetResult
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        [StringLength(3)]
        public string CurrencyCode { get; set; }
        [StringLength(50)]
        public string Channel { get; set; }
        public Guid? AnonymousId { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        [StringLength(10)]
        public string Locale { get; set; }
        [StringLength(2)]
        public string CountryCode { get; set; }
        public byte[] Version { get; set; }
    }
}
