// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using StockService.Infrastructure.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace StockService.Infrastructure.Persistence
{
    public partial interface IStockServiceDbContextProcedures
    {
        Task<int> SP_AdjustStockAsync(Guid? stockItemId, int? adjustmentQuantity, string reason, Guid? performedBy, Guid? approvedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ApplyAuditVarianceAsync(Guid? auditItemId, Guid? performedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_CommitStockReservationAsync(Guid? reservationId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_CompleteStockTransferAsync(Guid? transferId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_CreateStockTransferAsync(Guid? fromWarehouseId, Guid? toWarehouseId, Guid? requestedBy, string notes, OutputParameter<Guid?> transferId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_DecreaseStockAsync(Guid? stockItemId, int? quantity, string reason, Guid? performedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ExpireStockBatchesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_FulfillBackorderAsync(Guid? backorderId, int? fulfilledQuantity, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetInventoryTurnoverResult>> SP_GetInventoryTurnoverAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GetStockAgingSummaryResult>> SP_GetStockAgingSummaryAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_IdentifyDeadStockResult>> SP_IdentifyDeadStockAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_IncreaseStockAsync(Guid? stockItemId, int? quantity, string reason, Guid? performedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_RecalculateSafetyStockAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ReceivePurchaseOrderItemAsync(Guid? pOItemId, int? receivedQuantity, Guid? performedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ReleaseExpiredReservationsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ReserveStockAsync(Guid? stockItemId, Guid? reservationId, int? quantity, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_TriggerLowStockAlertsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_TriggerOverStockAlertsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
