// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class InboxMessage
{
    public Guid InboxMessageId { get; set; }

    public Guid ExternalMessageId { get; set; }

    public string MessageType { get; set; }

    public DateTime ReceivedAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public string Headers { get; set; }

    public byte[] RowVersion { get; set; }
}