// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class OutboxMessage
{
    public Guid OutboxMessageId { get; set; }

    public string MessageType { get; set; }

    public string Payload { get; set; }

    public string Headers { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public string Error { get; set; }

    public int Retries { get; set; }

    public byte[] RowVersion { get; set; }
}