// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class PurchaseOrder
{
    public Guid PurchaseOrderId { get; set; }

    public string Ponumber { get; set; }

    public Guid SupplierId { get; set; }

    public Guid WarehouseId { get; set; }

    public string OrderStatus { get; set; }

    public DateTime OrderDate { get; set; }

    public DateTime? ExpectedDeliveryDate { get; set; }

    public DateTime? ActualDeliveryDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Notes { get; set; }

    public Guid? CreatedBy { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; } = new List<PurchaseOrderItem>();

    public virtual Supplier Supplier { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}