// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class StockReservation
{
    public Guid ReservationId { get; set; }

    public Guid StockItemId { get; set; }

    public Guid? CartId { get; set; }

    public Guid? OrderId { get; set; }

    public Guid? CustomerId { get; set; }

    public int ReservedQuantity { get; set; }

    public string ReservationStatus { get; set; }

    public DateTime ReservedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public DateTime? ReleasedAt { get; set; }

    public string ReservationType { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual StockItem StockItem { get; set; }
}