// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class StockAuditItem
{
    public Guid AuditItemId { get; set; }

    public Guid AuditId { get; set; }

    public Guid StockItemId { get; set; }

    public int SystemQuantity { get; set; }

    public int CountedQuantity { get; set; }

    public int Variance { get; set; }

    public string VarianceReason { get; set; }

    public bool Adjusted { get; set; }

    public DateTime? CountedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual StockAudit Audit { get; set; }

    public virtual StockItem StockItem { get; set; }
}