// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class StockAllocationRule
{
    public Guid RuleId { get; set; }

    public string RuleName { get; set; }

    public int Priority { get; set; }

    public string AllocationType { get; set; }

    public string Conditions { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }
}