// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class StockAlert
{
    public Guid AlertId { get; set; }

    public Guid StockItemId { get; set; }

    public string AlertType { get; set; }

    public string AlertStatus { get; set; }

    public DateTime TriggeredAt { get; set; }

    public Guid? AcknowledgedBy { get; set; }

    public DateTime? AcknowledgedAt { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public string Message { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual StockItem StockItem { get; set; }
}