// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class StockMovement
{
    public Guid MovementId { get; set; }

    public Guid StockItemId { get; set; }

    public string MovementType { get; set; }

    public Guid? FromWarehouseId { get; set; }

    public Guid? ToWarehouseId { get; set; }

    public int Quantity { get; set; }

    public string ReferenceType { get; set; }

    public Guid? ReferenceId { get; set; }

    public string Reason { get; set; }

    public Guid? PerformedBy { get; set; }

    public DateTime MovementDate { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual StockItem StockItem { get; set; }
}