// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class StockItem
{
    public Guid StockItemId { get; set; }

    public Guid ProductId { get; set; }

    public Guid? VariationId { get; set; }

    public Guid WarehouseId { get; set; }

    public string Sku { get; set; }

    public int AvailableQuantity { get; set; }

    public int ReservedQuantity { get; set; }

    public int InTransitQuantity { get; set; }

    public int DamagedQuantity { get; set; }

    public int? MinimumStockLevel { get; set; }

    public int? MaximumStockLevel { get; set; }

    public int? ReorderQuantity { get; set; }

    public decimal? UnitCost { get; set; }

    public DateTime? LastRestockedAt { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public string BatchNumber { get; set; }

    public string BinLocation { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<StockAdjustment> StockAdjustments { get; set; } = new List<StockAdjustment>();

    public virtual ICollection<StockAlert> StockAlerts { get; set; } = new List<StockAlert>();

    public virtual ICollection<StockAuditItem> StockAuditItems { get; set; } = new List<StockAuditItem>();

    public virtual ICollection<StockMovement> StockMovements { get; set; } = new List<StockMovement>();

    public virtual ICollection<StockReservation> StockReservations { get; set; } = new List<StockReservation>();

    public virtual ICollection<StockTransferItem> StockTransferItems { get; set; } = new List<StockTransferItem>();

    public virtual Warehouse Warehouse { get; set; }
}