// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class StockTransferItem
{
    public Guid TransferItemId { get; set; }

    public Guid TransferId { get; set; }

    public Guid StockItemId { get; set; }

    public int RequestedQuantity { get; set; }

    public int? ShippedQuantity { get; set; }

    public int? ReceivedQuantity { get; set; }

    public int? DamagedQuantity { get; set; }

    public DateTime CreatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual StockItem StockItem { get; set; }

    public virtual StockTransfer Transfer { get; set; }
}