// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class StockAudit
{
    public Guid AuditId { get; set; }

    public Guid WarehouseId { get; set; }

    public string AuditType { get; set; }

    public string AuditStatus { get; set; }

    public DateTime? ScheduledDate { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public Guid? PerformedBy { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<StockAuditItem> StockAuditItems { get; set; } = new List<StockAuditItem>();

    public virtual Warehouse Warehouse { get; set; }
}