// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class Supplier
{
    public Guid SupplierId { get; set; }

    public string SupplierName { get; set; }

    public string SupplierCode { get; set; }

    public string ContactPerson { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string PaymentTerms { get; set; }

    public int? LeadTimeDays { get; set; }

    public int? MinimumOrderQuantity { get; set; }

    public bool IsActive { get; set; }

    public decimal? Rating { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();
}