// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class VwBackorderSummary
{
    public Guid BackorderId { get; set; }

    public Guid OrderId { get; set; }

    public Guid ProductId { get; set; }

    public int RequestedQuantity { get; set; }

    public int? FulfilledQuantity { get; set; }

    public int? RemainingQty { get; set; }

    public string BackorderStatus { get; set; }

    public DateTime? ExpectedFulfillmentDate { get; set; }
}