// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class VwPurchaseOrderStatus
{
    public Guid PurchaseOrderId { get; set; }

    public string Ponumber { get; set; }

    public string OrderStatus { get; set; }

    public Guid WarehouseId { get; set; }

    public DateTime? ExpectedDeliveryDate { get; set; }

    public DateTime? ActualDeliveryDate { get; set; }

    public int? TotalOrdered { get; set; }

    public int? TotalReceived { get; set; }
}