// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class VwStockMovementHistory
{
    public Guid MovementId { get; set; }

    public Guid StockItemId { get; set; }

    public Guid ProductId { get; set; }

    public Guid WarehouseId { get; set; }

    public string MovementType { get; set; }

    public int Quantity { get; set; }

    public DateTime MovementDate { get; set; }

    public string Reason { get; set; }

    public string ReferenceType { get; set; }

    public Guid? ReferenceId { get; set; }
}