// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class VwStockTransferStatus
{
    public Guid TransferId { get; set; }

    public Guid FromWarehouseId { get; set; }

    public Guid ToWarehouseId { get; set; }

    public string TransferStatus { get; set; }

    public DateTime? ShippedAt { get; set; }

    public DateTime? ReceivedAt { get; set; }

    public DateTime? EstimatedArrival { get; set; }

    public string TrackingNumber { get; set; }

    public int? TransferItemCount { get; set; }
}