// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class VwStockAvailableByWarehouse
{
    public Guid StockItemId { get; set; }

    public Guid ProductId { get; set; }

    public Guid WarehouseId { get; set; }

    public string WarehouseName { get; set; }

    public string WarehouseCode { get; set; }

    public int AvailableQuantity { get; set; }

    public int ReservedQuantity { get; set; }

    public int InTransitQuantity { get; set; }

    public int DamagedQuantity { get; set; }

    public int? MinimumStockLevel { get; set; }

    public int? MaximumStockLevel { get; set; }

    public DateTime? LastRestockedAt { get; set; }
}