// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class VwStockAdjustmentHistory
{
    public Guid AdjustmentId { get; set; }

    public Guid StockItemId { get; set; }

    public Guid ProductId { get; set; }

    public Guid WarehouseId { get; set; }

    public string AdjustmentType { get; set; }

    public int QuantityBefore { get; set; }

    public int QuantityAfter { get; set; }

    public int AdjustmentQuantity { get; set; }

    public string Reason { get; set; }

    public Guid? ApprovedBy { get; set; }

    public Guid? PerformedBy { get; set; }

    public DateTime AdjustmentDate { get; set; }
}