// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class VwStockReservationStatus
{
    public Guid ReservationId { get; set; }

    public Guid StockItemId { get; set; }

    public int ReservedQuantity { get; set; }

    public string ReservationStatus { get; set; }

    public DateTime ReservedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public string ReservationType { get; set; }

    public Guid ProductId { get; set; }

    public Guid WarehouseId { get; set; }
}