// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockService.Domain.Entities;

public partial class Warehouse
{
    public Guid WarehouseId { get; set; }

    public string WarehouseName { get; set; }

    public string WarehouseCode { get; set; }

    public string Address { get; set; }

    public string Type { get; set; }

    public bool IsActive { get; set; }

    public int Priority { get; set; }

    public int? Capacity { get; set; }

    public string ContactDetails { get; set; }

    public string OperatingHours { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();

    public virtual ICollection<StockAudit> StockAudits { get; set; } = new List<StockAudit>();

    public virtual ICollection<StockItem> StockItems { get; set; } = new List<StockItem>();

    public virtual ICollection<StockTransfer> StockTransferFromWarehouses { get; set; } = new List<StockTransfer>();

    public virtual ICollection<StockTransfer> StockTransferToWarehouses { get; set; } = new List<StockTransfer>();
}