// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CatalogService.Infrastructure;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CatalogService.Infrastructure.Persistence
{
    public partial class CatalogServiceDbContext
    {
        private ICatalogServiceDbContextProcedures _procedures;

        public virtual ICatalogServiceDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CatalogServiceDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICatalogServiceDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class CatalogServiceDbContextProcedures : ICatalogServiceDbContextProcedures
    {
        private readonly CatalogServiceDbContext _context;

        public CatalogServiceDbContextProcedures(CatalogServiceDbContext context)
        {
            _context = context;
        }

        public virtual async Task<int> SP_Brand_CreateAsync(string name, string slug, string description, OutputParameter<int?> newBrandId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterNewBrandId = new SqlParameter
            {
                ParameterName = "NewBrandId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = newBrandId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Name",
                    Size = 400,
                    Value = name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Slug",
                    Size = 400,
                    Value = slug ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Description",
                    Size = 2000,
                    Value = description ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterNewBrandId,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Brand_Create] @Name = @Name, @Slug = @Slug, @Description = @Description, @NewBrandId = @NewBrandId OUTPUT", sqlParameters, cancellationToken);

            newBrandId?.SetValue(parameterNewBrandId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_BulkImportJob_CreateAsync(string fileName, int? totalRows, OutputParameter<int?> newJobId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterNewJobId = new SqlParameter
            {
                ParameterName = "NewJobId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = newJobId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FileName",
                    Size = 1000,
                    Value = fileName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TotalRows",
                    Value = totalRows ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterNewJobId,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_BulkImportJob_Create] @FileName = @FileName, @TotalRows = @TotalRows, @NewJobId = @NewJobId OUTPUT", sqlParameters, cancellationToken);

            newJobId?.SetValue(parameterNewJobId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_Category_CreateAsync(string name, string slug, string description, int? parentCategoryId, string createdBy, OutputParameter<int?> newCategoryId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterNewCategoryId = new SqlParameter
            {
                ParameterName = "NewCategoryId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = newCategoryId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Name",
                    Size = 400,
                    Value = name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Slug",
                    Size = 400,
                    Value = slug ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Description",
                    Size = 2000,
                    Value = description ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ParentCategoryId",
                    Value = parentCategoryId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CreatedBy",
                    Size = 200,
                    Value = createdBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterNewCategoryId,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Category_Create] @Name = @Name, @Slug = @Slug, @Description = @Description, @ParentCategoryId = @ParentCategoryId, @CreatedBy = @CreatedBy, @NewCategoryId = @NewCategoryId OUTPUT", sqlParameters, cancellationToken);

            newCategoryId?.SetValue(parameterNewCategoryId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_Inbox_AddAsync(string messageId, string handler, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "MessageId",
                    Size = 400,
                    Value = messageId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Handler",
                    Size = 400,
                    Value = handler ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Inbox_Add] @MessageId = @MessageId, @Handler = @Handler", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_InventorySnapshot_UpsertAsync(int? skuId, string warehouseId, int? quantityAvailable, int? quantityReserved, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "SkuId",
                    Value = skuId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "WarehouseId",
                    Size = 100,
                    Value = warehouseId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "QuantityAvailable",
                    Value = quantityAvailable ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "QuantityReserved",
                    Value = quantityReserved ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_InventorySnapshot_Upsert] @SkuId = @SkuId, @WarehouseId = @WarehouseId, @QuantityAvailable = @QuantityAvailable, @QuantityReserved = @QuantityReserved", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_Outbox_InsertAsync(string eventType, string payload, string correlationId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "EventType",
                    Size = 500,
                    Value = eventType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Payload",
                    Size = -1,
                    Value = payload ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CorrelationId",
                    Size = 200,
                    Value = correlationId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Outbox_Insert] @EventType = @EventType, @Payload = @Payload, @CorrelationId = @CorrelationId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_Outbox_MarkProcessedAsync(int? outboxId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "OutboxId",
                    Value = outboxId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Outbox_MarkProcessed] @OutboxId = @OutboxId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_Product_CreateFullAsync(string name, string slug, string shortDescription, string longDescription, int? brandId, int? manufacturerId, int? categoryId, string primaryImageUrl, string createdBy, string variantsJson, string imagesJson, string attributesJson, string tagSlugs, string outboxCorrelationId, OutputParameter<int?> newProductId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterNewProductId = new SqlParameter
            {
                ParameterName = "NewProductId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = newProductId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Name",
                    Size = 500,
                    Value = name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Slug",
                    Size = 500,
                    Value = slug ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ShortDescription",
                    Size = 2000,
                    Value = shortDescription ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LongDescription",
                    Size = -1,
                    Value = longDescription ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "BrandId",
                    Value = brandId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ManufacturerId",
                    Value = manufacturerId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CategoryId",
                    Value = categoryId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PrimaryImageUrl",
                    Size = 2000,
                    Value = primaryImageUrl ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CreatedBy",
                    Size = 200,
                    Value = createdBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "VariantsJson",
                    Size = -1,
                    Value = variantsJson ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ImagesJson",
                    Size = -1,
                    Value = imagesJson ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "AttributesJson",
                    Size = -1,
                    Value = attributesJson ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TagSlugs",
                    Size = -1,
                    Value = tagSlugs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "OutboxCorrelationId",
                    Size = 200,
                    Value = outboxCorrelationId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterNewProductId,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Product_CreateFull] @Name = @Name, @Slug = @Slug, @ShortDescription = @ShortDescription, @LongDescription = @LongDescription, @BrandId = @BrandId, @ManufacturerId = @ManufacturerId, @CategoryId = @CategoryId, @PrimaryImageUrl = @PrimaryImageUrl, @CreatedBy = @CreatedBy, @VariantsJson = @VariantsJson, @ImagesJson = @ImagesJson, @AttributesJson = @AttributesJson, @TagSlugs = @TagSlugs, @OutboxCorrelationId = @OutboxCorrelationId, @NewProductId = @NewProductId OUTPUT", sqlParameters, cancellationToken);

            newProductId?.SetValue(parameterNewProductId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_Product_DeleteAsync(int? productId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ProductId",
                    Value = productId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Product_Delete] @ProductId = @ProductId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_Product_GetByIdResult>> SP_Product_GetByIdAsync(int? productId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ProductId",
                    Value = productId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_Product_GetByIdResult>("EXEC @returnValue = [dbo].[SP_Product_GetById] @ProductId = @ProductId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_Product_PublishAsync(int? productId, string publishedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ProductId",
                    Value = productId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PublishedBy",
                    Size = 200,
                    Value = publishedBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Product_Publish] @ProductId = @ProductId, @PublishedBy = @PublishedBy", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_Product_SearchResult>> SP_Product_SearchAsync(string query, int? categoryId, int? brandId, decimal? minPrice, decimal? maxPrice, string tag, bool? onlyPublished, int? page, int? pageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Query",
                    Size = 800,
                    Value = query ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CategoryId",
                    Value = categoryId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "BrandId",
                    Value = brandId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MinPrice",
                    Precision = 18,
                    Scale = 2,
                    Value = minPrice ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "MaxPrice",
                    Precision = 18,
                    Scale = 2,
                    Value = maxPrice ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Tag",
                    Size = 400,
                    Value = tag ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "OnlyPublished",
                    Value = onlyPublished ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "Page",
                    Value = page ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PageSize",
                    Value = pageSize ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_Product_SearchResult>("EXEC @returnValue = [dbo].[SP_Product_Search] @Query = @Query, @CategoryId = @CategoryId, @BrandId = @BrandId, @MinPrice = @MinPrice, @MaxPrice = @MaxPrice, @Tag = @Tag, @OnlyPublished = @OnlyPublished, @Page = @Page, @PageSize = @PageSize", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_Product_UpdateAsync(int? productId, string name, string slug, string shortDescription, string longDescription, int? brandId, int? categoryId, string primaryImageUrl, string lastModifiedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ProductId",
                    Value = productId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Name",
                    Size = 500,
                    Value = name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Slug",
                    Size = 500,
                    Value = slug ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ShortDescription",
                    Size = 2000,
                    Value = shortDescription ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LongDescription",
                    Size = -1,
                    Value = longDescription ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "BrandId",
                    Value = brandId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "CategoryId",
                    Value = categoryId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PrimaryImageUrl",
                    Size = 2000,
                    Value = primaryImageUrl ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "LastModifiedBy",
                    Size = 200,
                    Value = lastModifiedBy ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Product_Update] @ProductId = @ProductId, @Name = @Name, @Slug = @Slug, @ShortDescription = @ShortDescription, @LongDescription = @LongDescription, @BrandId = @BrandId, @CategoryId = @CategoryId, @PrimaryImageUrl = @PrimaryImageUrl, @LastModifiedBy = @LastModifiedBy", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_ProductPromotion_AddAsync(int? productId, int? promotionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ProductId",
                    Value = productId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PromotionId",
                    Value = promotionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_ProductPromotion_Add] @ProductId = @ProductId, @PromotionId = @PromotionId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_ProductSearch_BySkuResult>> SP_ProductSearch_BySkuAsync(string sku, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Sku",
                    Size = 200,
                    Value = sku ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_ProductSearch_BySkuResult>("EXEC @returnValue = [dbo].[SP_ProductSearch_BySku] @Sku = @Sku", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_ProductVariant_AddOrUpdateAsync(int? skuId, int? productId, string sku, string barcode, string attributes, decimal? unitPrice, string currency, bool? isDefault, OutputParameter<int?> newSkuId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterNewSkuId = new SqlParameter
            {
                ParameterName = "NewSkuId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = newSkuId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "SkuId",
                    Value = skuId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "ProductId",
                    Value = productId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Sku",
                    Size = 200,
                    Value = sku ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Barcode",
                    Size = 200,
                    Value = barcode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Attributes",
                    Size = 4000,
                    Value = attributes ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "UnitPrice",
                    Precision = 18,
                    Scale = 2,
                    Value = unitPrice ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Currency",
                    Size = 20,
                    Value = currency ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IsDefault",
                    Value = isDefault ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterNewSkuId,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_ProductVariant_AddOrUpdate] @SkuId = @SkuId, @ProductId = @ProductId, @Sku = @Sku, @Barcode = @Barcode, @Attributes = @Attributes, @UnitPrice = @UnitPrice, @Currency = @Currency, @IsDefault = @IsDefault, @NewSkuId = @NewSkuId OUTPUT", sqlParameters, cancellationToken);

            newSkuId?.SetValue(parameterNewSkuId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SP_Promotion_CreateAsync(string name, string code, string description, byte? discountType, decimal? discountValue, bool? appliesToAllProducts, DateTime? startDate, DateTime? endDate, OutputParameter<int?> newPromotionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterNewPromotionId = new SqlParameter
            {
                ParameterName = "NewPromotionId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = newPromotionId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Name",
                    Size = 500,
                    Value = name ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Code",
                    Size = 100,
                    Value = code ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Description",
                    Size = 2000,
                    Value = description ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DiscountType",
                    Value = discountType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.TinyInt,
                },
                new SqlParameter
                {
                    ParameterName = "DiscountValue",
                    Precision = 18,
                    Scale = 4,
                    Value = discountValue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "AppliesToAllProducts",
                    Value = appliesToAllProducts ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "StartDate",
                    Scale = 7,
                    Value = startDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                new SqlParameter
                {
                    ParameterName = "EndDate",
                    Scale = 7,
                    Value = endDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime2,
                },
                parameterNewPromotionId,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SP_Promotion_Create] @Name = @Name, @Code = @Code, @Description = @Description, @DiscountType = @DiscountType, @DiscountValue = @DiscountValue, @AppliesToAllProducts = @AppliesToAllProducts, @StartDate = @StartDate, @EndDate = @EndDate, @NewPromotionId = @NewPromotionId OUTPUT", sqlParameters, cancellationToken);

            newPromotionId?.SetValue(parameterNewPromotionId.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_Stats_GetSummaryResult>> SP_Stats_GetSummaryAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SP_Stats_GetSummaryResult>("EXEC @returnValue = [dbo].[SP_Stats_GetSummary]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
