// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CatalogService.Infrastructure;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CatalogService.Infrastructure.Persistence
{
    public partial interface ICatalogServiceDbContextProcedures
    {
        Task<int> SP_Brand_CreateAsync(string name, string slug, string description, OutputParameter<int?> newBrandId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_BulkImportJob_CreateAsync(string fileName, int? totalRows, OutputParameter<int?> newJobId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Category_CreateAsync(string name, string slug, string description, int? parentCategoryId, string createdBy, OutputParameter<int?> newCategoryId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Inbox_AddAsync(string messageId, string handler, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_InventorySnapshot_UpsertAsync(int? skuId, string warehouseId, int? quantityAvailable, int? quantityReserved, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Outbox_InsertAsync(string eventType, string payload, string correlationId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Outbox_MarkProcessedAsync(int? outboxId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Product_CreateFullAsync(string name, string slug, string shortDescription, string longDescription, int? brandId, int? manufacturerId, int? categoryId, string primaryImageUrl, string createdBy, string variantsJson, string imagesJson, string attributesJson, string tagSlugs, string outboxCorrelationId, OutputParameter<int?> newProductId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Product_DeleteAsync(int? productId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_Product_GetByIdResult>> SP_Product_GetByIdAsync(int? productId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Product_PublishAsync(int? productId, string publishedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_Product_SearchResult>> SP_Product_SearchAsync(string query, int? categoryId, int? brandId, decimal? minPrice, decimal? maxPrice, string tag, bool? onlyPublished, int? page, int? pageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Product_UpdateAsync(int? productId, string name, string slug, string shortDescription, string longDescription, int? brandId, int? categoryId, string primaryImageUrl, string lastModifiedBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ProductPromotion_AddAsync(int? productId, int? promotionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ProductSearch_BySkuResult>> SP_ProductSearch_BySkuAsync(string sku, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ProductVariant_AddOrUpdateAsync(int? skuId, int? productId, string sku, string barcode, string attributes, decimal? unitPrice, string currency, bool? isDefault, OutputParameter<int?> newSkuId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_Promotion_CreateAsync(string name, string code, string description, byte? discountType, decimal? discountValue, bool? appliesToAllProducts, DateTime? startDate, DateTime? endDate, OutputParameter<int?> newPromotionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_Stats_GetSummaryResult>> SP_Stats_GetSummaryAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
